-- Masterpiece v04 Script 
-- DATA 620 
-- Written by Carrie Beam for UMGC April 2020
-- Script to remove any existing schema called 'masterpiece' and then create 
-- and populate a single-table database for SQL query

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema masterpiece
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `masterpiece` ;

-- -----------------------------------------------------
-- Schema masterpiece
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `masterpiece` DEFAULT CHARACTER SET utf8 ;
USE `masterpiece` ;

-- -----------------------------------------------------
-- Table `masterpiece`.`LitCharacters`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `masterpiece`.`LitCharacters` ;

CREATE TABLE IF NOT EXISTS `masterpiece`.`LitCharacters` (
  `idLitCharacters` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `Realm` VARCHAR(45) NULL,
  `CreatureType` VARCHAR(45) NULL,
  `CreatureSubType` VARCHAR(45) NULL,
  `Gender` VARCHAR(45) NULL,
  `Height` INT NULL,
  `Weight` INT NULL,
  `Appearances` INT NULL,
  PRIMARY KEY (`idLitCharacters`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO `masterpiece`.`litcharacters` (`Name`, `Realm`, `CreatureType`, `CreatureSubType`, `Gender`, `Height`, `Weight`,`Appearances`) VALUES 
('Kaerio', 'Magical', 'Human', 'Merman', 'Male', '67', '194','10'),
('Lituck', 'Magical', 'Other', 'Gargoyle', 'Male', '42', '258','9'),
('Hissing Hornet', 'Real', 'Human', 'Supervillain', 'Male', '61', '205','5'),
('Rugby Defiant Eldon', 'Real', 'Human', 'Pirate', 'Male', '67', '168','0'),
('Belet the Hero', 'Real', 'Human', 'Knight', 'Female', '70', '270','4'),
('Mistress Shaggy Wraith', 'Real', 'Human', 'Supervillain', 'Female', '66', '175','0'),
('Swift Shadow', 'Real', 'Human', 'Supervillain', 'Female', '83', '179','1'),
('Doctor Heavenly Daggers', 'Real', 'Human', 'Superhero', 'Female', '89', '183','0'),
('Carpus Jesterrose', 'Magical', 'Human', 'Fairy', 'Male', '11', '5','7'),
('Wilhelmine Slayer England', 'Real', 'Human', 'Pirate', 'Female', '70', '136','0'),
('Saffron Copperspeck', 'Magical', 'Human', 'Fairy', 'Female', '12', '6','0'),
('Leonore The Wall Clive', 'Real', 'Human', 'Pirate', 'Female', '66', '133','9'),
('Oceane', 'Magical', 'Human', 'Mermaid', 'Female', '60', '112','0'),
('Scarlet Almonddove', 'Magical', 'Human', 'Fairy', 'Female', '14', '5','5'),
('Courage', 'Magical', 'Animal', 'Wolpertinger', 'Male', '11', '8','0'),
('Doria', 'Magical', 'Human', 'Mermaid', 'Female', '67', '124','5'),
('Delmara', 'Magical', 'Human', 'Mermaid', 'Female', '60', '126','0'),
('Cosmos', 'Magical', 'Animal', 'Jackalope', 'Female', '10', '9','2'),
('Dr. Deficit', 'Real', 'Human', 'Mad Scientist', 'Female', '72', '139','0'),
('Truffle', 'Magical', 'Animal', 'Jackalope', 'Male', '13', '8','0'),
('Lula Stormrider Williams', 'Real', 'Human', 'Cowgirl', 'Female', '64', '126','0'),
('Superchelosaurus (Super Claw Lizard)', 'Real', 'Animal', 'Dinosaur', 'Female', '202', '26974','0'),
('Prof. Queasy', 'Real', 'Human', 'Mad Scientist', 'Male', '72', '142','0'),
('The Voiceless Arsonist', 'Real', 'Human', 'Supervillain', 'Female', '58', '184','9'),
('Moonbean Mistyweather', 'Magical', 'Human', 'Fairy', 'Male', '11', '4','0'),
('Solstice', 'Magical', 'Animal', 'Wolpertinger', 'Female', '11', '7','0'),
('Cool Mongoose', 'Real', 'Human', 'Superhero', 'Female', '81', '148','3'),
('Water Raven', 'Real', 'Human', 'Superhero', 'Male', '83', '140','4'),
('James the Friendly Brooks', 'Real', 'Human', 'Cowboy', 'Male', '69', '133','4'),
('Alectrochelodraco (Eagle Claw Dragon)', 'Real', 'Animal', 'Dinosaur', 'Male', '207', '7409','9'),
('Sechec', 'Magical', 'Animal', 'Basilisk', 'Male', '419', '283','0'),
('Pelorospondylus (Monstrous Vertebrae)', 'Real', 'Animal', 'Dinosaur', 'Female', '228', '17477','0'),
('Fern Auger Flowers', 'Real', 'Human', 'Cowgirl', 'Female', '64', '130','5'),
('Lord Eager Shield', 'Real', 'Human', 'Superhero', 'Male', '71', '187','0'),
('Sojisnux', 'Magical', 'Other', 'Gargoyle', 'Female', '39', '103','0'),
('Nugget', 'Magical', 'Animal', 'Jackalope', 'Female', '12', '9','0'),
('Dr. Thunder', 'Real', 'Human', 'Mad Scientist', 'Female', '71', '138','5'),
('Prof. Stitch', 'Real', 'Human', 'Mad Scientist', 'Male', '69', '146','9'),
('Lela Dynamite Lowery', 'Real', 'Human', 'Cowgirl', 'Female', '62', '131','2'),
('Vanessa Birdfog', 'Magical', 'Human', 'Fairy', 'Female', '11', '6','0'),
('Barbara Foxpool', 'Magical', 'Human', 'Fairy', 'Female', '12', '6','0'),
('Prof. Outcome', 'Real', 'Human', 'Mad Scientist', 'Female', '68', '157','0'),
('Eldoris', 'Magical', 'Human', 'Mermaid', 'Female', '64', '124','0'),
('Uzconom', 'Magical', 'Other', 'Gargoyle', 'Male', '31', '249','9'),
('Kawai', 'Magical', 'Human', 'Merman', 'Male', '72', '206','0'),
('Gnevumo', 'Magical', 'Other', 'Gargoyle', 'Female', '38', '164','0'),
('Doctor Spectacular Whiz', 'Real', 'Human', 'Supervillain', 'Male', '65', '164','1'),
('Jade', 'Magical', 'Animal', 'Jackalope', 'Male', '12', '5','0'),
('Vuejezli', 'Magical', 'Other', 'Gargoyle', 'Female', '32', '185','0'),
('Osharus', 'Magical', 'Human', 'Merman', 'Male', '65', '206','5'),
('Amara', 'Magical', 'Human', 'Mermaid', 'Female', '61', '135','10'),
('Prof. Fluke', 'Real', 'Human', 'Mad Scientist', 'Male', '70', '145','5'),
('Bionic First Aid Prototype', 'Real', 'Other', 'Robot', 'Unknown', '48', '139','0'),
('Lethal Lynx', 'Real', 'Human', 'Supervillain', 'Female', '68', '190','0'),
('Manuela No-Tongue Layre', 'Real', 'Human', 'Pirate', 'Female', '69', '146','3'),
('Magnum', 'Magical', 'Animal', 'Wolpertinger', 'Female', '13', '9','4'),
('Odolina the Bold', 'Real', 'Human', 'Knight', 'Female', '75', '265','0'),
('Rational Space Navigation Machine', 'Real', 'Other', 'Robot', 'Unknown', '54', '112','0'),
('Dr. Pungent', 'Real', 'Human', 'Mad Scientist', 'Female', '69', '160','0'),
('Cloud Limelily', 'Magical', 'Human', 'Fairy', 'Female', '10', '6','0'),
('Aldis', 'Magical', 'Human', 'Dryad', 'Female', '64', '119','0'),
('Violent Spider', 'Real', 'Human', 'Supervillain', 'Female', '80', '203','0'),
('Forbes Reaper Spaulding', 'Real', 'Human', 'Pirate', 'Male', '67', '156','0'),
('Arnold Smokes Stevenson', 'Real', 'Human', 'Cowboy', 'Male', '68', '151','6'),
('Richemanus the Shepherd', 'Real', 'Human', 'Knight', 'Male', '62', '310','0'),
('Dr. Boulder', 'Real', 'Human', 'Mad Scientist', 'Female', '71', '155','6'),
('Serissa', 'Magical', 'Human', 'Dryad', 'Female', '62', '123','0'),
('Zaatruarad', 'Magical', 'Other', 'Gargoyle', 'Male', '38', '217','0'),
('Jarrett Reaper Clayden', 'Real', 'Human', 'Pirate', 'Male', '71', '150','9'),
('The Bronze Swan', 'Real', 'Human', 'Superhero', 'Male', '73', '230','0'),
('Strategic Human Protection Golem', 'Real', 'Other', 'Robot', 'Unknown', '33', '156','0'),
('Solace', 'Magical', 'Animal', 'Wolpertinger', 'Male', '12', '5','0'),
('Nireta', 'Magical', 'Human', 'Mermaid', 'Female', '66', '111','4'),
('Wallace the Blind Rich', 'Real', 'Human', 'Cowboy', 'Male', '71', '138','0'),
('Tangy Tigermist', 'Magical', 'Human', 'Fairy', 'Male', '13', '5','0'),
('Shothi', 'Magical', 'Other', 'Gargoyle', 'Female', '36', '252','10'),
('White Oxman', 'Real', 'Human', 'Superhero', 'Male', '61', '173','0'),
('Violet Bear', 'Real', 'Human', 'Supervillain', 'Female', '59', '236','2'),
('The Copper Amazon', 'Real', 'Human', 'Superhero', 'Female', '83', '182','0'),
('Jone the Bane', 'Real', 'Human', 'Knight', 'Female', '71', '207','0'),
('Dr. Goose', 'Real', 'Human', 'Mad Scientist', 'Male', '67', '134','0'),
('The Wacky Wraith', 'Real', 'Human', 'Supervillain', 'Female', '57', '202','0'),
('Raamar', 'Magical', 'Other', 'Gargoyle', 'Male', '33', '286','0'),
('The Fantastic Phoenix', 'Real', 'Human', 'Superhero', 'Female', '70', '174','3'),
('Mister White Sage', 'Real', 'Human', 'Superhero', 'Male', '78', '200','0'),
('Self-Reliant Sabotage Entity', 'Real', 'Other', 'Robot', 'Unknown', '61', '122','0'),
('Cari', 'Magical', 'Human', 'Merman', 'Male', '61', '182','0'),
('Willoa', 'Magical', 'Human', 'Dryad', 'Female', '62', '129','0'),
('Alma Big Bazoo Pierce', 'Real', 'Human', 'Cowgirl', 'Female', '66', '117','0'),
('Myrtle Jeopardy Sherman', 'Real', 'Human', 'Cowgirl', 'Female', '62', '149','0'),
('Kendall', 'Magical', 'Human', 'Merman', 'Male', '67', '117','0'),
('Winifred the Silence', 'Real', 'Human', 'Knight', 'Female', '68', '292','4'),
('Yinzu', 'Magical', 'Animal', 'Basilisk', 'Male', '519', '685','10'),
('The Gray Gorilla', 'Real', 'Human', 'Supervillain', 'Male', '81', '220','0'),
('Deinocephaloceratops (Terrible Horned Face)', 'Real', 'Animal', 'Dinosaur', 'Male', '210', '23760','9'),
('Prof. Maniac', 'Real', 'Human', 'Mad Scientist', 'Male', '68', '149','4'),
('Sobejul', 'Magical', 'Other', 'Gargoyle', 'Female', '44', '229','4'),
('Ollie Friendly Face Jenkins', 'Real', 'Human', 'Cowgirl', 'Female', '63', '115','1'),
('Newt Redfur', 'Magical', 'Human', 'Fairy', 'Male', '14', '6','0'),
('Homochelobator (Same Claw Hero)', 'Real', 'Animal', 'Dinosaur', 'Male', '203', '23456','0'),
('Faramond the Eager', 'Real', 'Human', 'Knight', 'Male', '68', '165','0'),
('Mistress Frozen Cheat', 'Real', 'Human', 'Supervillain', 'Female', '86', '145','0'),
('Rational Life Simulation Device', 'Real', 'Other', 'Robot', 'Unknown', '47', '100','0'),
('Brutus', 'Magical', 'Animal', 'Wolpertinger', 'Male', '12', '11','0'),
('Stareye', 'Real', 'Human', 'Superhero', 'Female', '70', '147','8'),
('Dr. Whistle', 'Real', 'Human', 'Mad Scientist', 'Female', '67', '142','9'),
('Agent Bronze Starling', 'Real', 'Human', 'Superhero', 'Female', '61', '257','0'),
('Barbarea', 'Magical', 'Human', 'Dryad', 'Female', '63', '102','0'),
('Elizabeth Jeopardy Ortiz', 'Real', 'Human', 'Cowgirl', 'Female', '66', '125','0'),
('Hugyica', 'Magical', 'Animal', 'Basilisk', 'Female', '487', '616','2'),
('Doctor Broken Sentinel', 'Real', 'Human', 'Superhero', 'Female', '71', '134','0'),
('Silvivenator (Forest Hunter)', 'Real', 'Animal', 'Dinosaur', 'Male', '215', '17692','10'),
('Sabadvux', 'Magical', 'Other', 'Gargoyle', 'Male', '40', '245','0'),
('The Crimson General', 'Real', 'Human', 'Superhero', 'Female', '55', '137','5'),
('Sensory Recording Technology', 'Real', 'Other', 'Robot', 'Unknown', '55', '167','0'),
('Gaura', 'Magical', 'Human', 'Dryad', 'Female', '68', '137','5'),
('Dr. Misery', 'Real', 'Human', 'Mad Scientist', 'Male', '69', '146','7'),
('Callan', 'Magical', 'Human', 'Mermaid', 'Female', '63', '115','3'),
('Torvorhynchomimus (Savage Beak Mimic)', 'Real', 'Animal', 'Dinosaur', 'Male', '209', '18827','0'),
('Shegeinzu', 'Magical', 'Animal', 'Basilisk', 'Female', '399', '579','2'),
('Alien Banshee', 'Real', 'Human', 'Supervillain', 'Male', '67', '145','10'),
('Universal Base Protection Android', 'Real', 'Other', 'Robot', 'Unknown', '48', '152','9'),
('The Broken Sage', 'Real', 'Human', 'Superhero', 'Male', '83', '157','10'),
('Magna Citrusstream', 'Magical', 'Human', 'Fairy', 'Female', '11', '5','3'),
('Prof. Bottom', 'Real', 'Human', 'Mad Scientist', 'Female', '68', '153','0'),
('Barracudon', 'Magical', 'Human', 'Merman', 'Male', '72', '141','5'),
('Winston One Eye Tack', 'Real', 'Human', 'Pirate', 'Male', '71', '163','0'),
('Rosia Golden-Eye Rave', 'Real', 'Human', 'Pirate', 'Female', '72', '154','3'),
('The Outrageous General', 'Real', 'Human', 'Superhero', 'Male', '82', '168','4'),
('Massodonceratops (Massive Tooth Horned Face)', 'Real', 'Animal', 'Dinosaur', 'Female', '233', '22647','0'),
('Prof. Fingers', 'Real', 'Human', 'Mad Scientist', 'Male', '73', '157','0'),
('Golden Bird Eye Carlton', 'Real', 'Human', 'Pirate', 'Female', '72', '133','9'),
('Monroe', 'Magical', 'Human', 'Merman', 'Male', '68', '197','4'),
('Doran of the Light', 'Real', 'Human', 'Knight', 'Male', '65', '227','0'),
('Yejazeq', 'Magical', 'Animal', 'Basilisk', 'Female', '537', '498','4'),
('Widget', 'Magical', 'Animal', 'Wolpertinger', 'Female', '12', '10','8'),
('Soleil Mistyspice', 'Magical', 'Human', 'Fairy', 'Female', '11', '4','8'),
('The Old Horror', 'Real', 'Human', 'Supervillain', 'Female', '75', '196','0'),
('Ukrih', 'Magical', 'Other', 'Gargoyle', 'Female', '35', '177','7'),
('Ed Phantom ONeill', 'Real', 'Human', 'Cowboy', 'Male', '70', '127','3'),
('Eluned the Grand', 'Real', 'Human', 'Knight', 'Female', '70', '297','0'),
('Quavolqaz', 'Magical', 'Other', 'Gargoyle', 'Male', '37', '218','8'),
('Self-Aware Algorithm Device', 'Real', 'Other', 'Robot', 'Unknown', '47', '152','5'),
('Milet the Illuminator', 'Real', 'Human', 'Knight', 'Male', '73', '281','0'),
('The Filthy Smasher', 'Real', 'Human', 'Supervillain', 'Female', '61', '157','0'),
('Prof. Craven', 'Real', 'Human', 'Mad Scientist', 'Female', '69', '138','5'),
('Leomaris', 'Magical', 'Human', 'Merman', 'Male', '68', '177','0'),
('Jubal', 'Magical', 'Human', 'Merman', 'Male', '72', '184','0'),
('Arvilla Mumbling Heinrik', 'Real', 'Human', 'Pirate', 'Female', '67', '144','0'),
('Pandora Cloudsplash', 'Magical', 'Human', 'Fairy', 'Male', '12', '4','0'),
('Dicraeotholus (Forked Dome)', 'Real', 'Animal', 'Dinosaur', 'Female', '173', '20907','0'),
('Julianne Giggleclove', 'Magical', 'Human', 'Fairy', 'Female', '14', '4','0'),
('Tammie the Romantic', 'Real', 'Human', 'Knight', 'Male', '67', '227','0'),
('Elva Butcher Barrie', 'Real', 'Human', 'Pirate', 'Female', '65', '148','0'),
('Selene Cottonbottom', 'Magical', 'Human', 'Fairy', 'Female', '13', '5','1'),
('Harbor Frozenshadow', 'Magical', 'Human', 'Fairy', 'Male', '11', '2','1'),
('Timber', 'Magical', 'Animal', 'Jackalope', 'Male', '11', '10','3'),
('Nero', 'Magical', 'Animal', 'Jackalope', 'Male', '11', '7','0'),
('Dr. Moon', 'Real', 'Human', 'Mad Scientist', 'Female', '67', '153','0'),
('Munchkin', 'Magical', 'Animal', 'Wolpertinger', 'Female', '12', '6','6'),
('Shaden', 'Real', 'Human', 'Superhero', 'Male', '77', '176','0'),
('Reef Jumpyjewel', 'Magical', 'Human', 'Fairy', 'Male', '10', '3','0'),
('The Fire Brute', 'Real', 'Human', 'Supervillain', 'Male', '56', '190','4'),
('Hadrodraco (Big Dragon)', 'Real', 'Animal', 'Dinosaur', 'Male', '229', '21459','3'),
('Sybbyl the Keen', 'Real', 'Human', 'Knight', 'Female', '69', '188','10'),
('Panochelogryphus (Fully Claw Griffin)', 'Real', 'Animal', 'Dinosaur', 'Female', '197', '15445','10'),
('The Wanderer', 'Real', 'Human', 'Supervillain', 'Male', '57', '235','0'),
('Vivien', 'Magical', 'Human', 'Mermaid', 'Female', '62', '117','1'),
('Laraine', 'Magical', 'Human', 'Mermaid', 'Female', '65', '120','0'),
('Suffield Deranged Hackney', 'Real', 'Human', 'Pirate', 'Male', '67', '160','0'),
('Dr. Effort', 'Real', 'Human', 'Mad Scientist', 'Male', '68', '137','1'),
('Intelligent Bodyguard Technician', 'Real', 'Other', 'Robot', 'Unknown', '45', '144','0'),
('Griritt', 'Magical', 'Other', 'Gargoyle', 'Male', '37', '244','9'),
('Carl Killer McPherson', 'Real', 'Human', 'Cowboy', 'Male', '69', '134','3'),
('Wallflower Whitewhirl', 'Magical', 'Human', 'Fairy', 'Female', '10', '4','0'),
('Zaqac', 'Magical', 'Animal', 'Basilisk', 'Male', '408', '428','8'),
('Jericho', 'Magical', 'Animal', 'Jackalope', 'Male', '11', '7','0'),
('Asbam', 'Magical', 'Other', 'Gargoyle', 'Male', '41', '148','0'),
('Guiscard the Gentle', 'Real', 'Human', 'Knight', 'Male', '66', '207','7'),
('Pelorotrachelotitan (Monstrous Necked Giant)', 'Real', 'Animal', 'Dinosaur', 'Female', '131', '16885','1'),
('Carrie the Mortal Sherman', 'Real', 'Human', 'Cowgirl', 'Female', '61', '119','2'),
('The Ice Doctor', 'Real', 'Human', 'Superhero', 'Female', '75', '178','0'),
('Grumpy Savage', 'Real', 'Human', 'Supervillain', 'Male', '72', '182','3'),
('Juggernaut', 'Magical', 'Animal', 'Wolpertinger', 'Male', '11', '7','2'),
('Dan Have Mercy Knowles', 'Real', 'Human', 'Cowboy', 'Male', '66', '175','0'),
('Eisesux', 'Magical', 'Animal', 'Basilisk', 'Female', '473', '576','0'),
('Newton The Honest Puck', 'Real', 'Human', 'Pirate', 'Male', '67', '148','0'),
('Jehen the Weak', 'Real', 'Human', 'Knight', 'Male', '72', '202','0'),
('Kunzu', 'Magical', 'Other', 'Gargoyle', 'Female', '37', '209','9'),
('Shusanna the Lion', 'Real', 'Human', 'Knight', 'Female', '77', '278','0'),
('Roesia the Reckless', 'Real', 'Human', 'Knight', 'Female', '65', '236','0'),
('Germath', 'Magical', 'Other', 'Gargoyle', 'Male', '39', '164','0'),
('The Broad Sentinel', 'Real', 'Human', 'Supervillain', 'Male', '65', '204','2'),
('Parsons Twitching Brady', 'Real', 'Human', 'Pirate', 'Male', '67', '137','8'),
('Brachiovenator (Arm Hunter)', 'Real', 'Animal', 'Dinosaur', 'Male', '215', '22255','0'),
('Ubo', 'Magical', 'Other', 'Gargoyle', 'Female', '36', '188','3'),
('Petiare', 'Magical', 'Human', 'Dryad', 'Female', '65', '122','0'),
('Cyrtodocus (Curved Neck)', 'Real', 'Animal', 'Dinosaur', 'Male', '180', '21672','7'),
('Dr. Fascination', 'Real', 'Human', 'Mad Scientist', 'Male', '69', '156','7'),
('Edwin Sureshot Alford', 'Real', 'Human', 'Cowboy', 'Male', '69', '141','5'),
('The Dark Detective', 'Real', 'Human', 'Superhero', 'Male', '41', '147','6'),
('Gomer Pirate Swail', 'Real', 'Human', 'Pirate', 'Male', '72', '148','8'),
('Mitah Copperclover', 'Magical', 'Human', 'Fairy', 'Male', '13', '4','4'),
('Camptochelolestes (Bent Claw Stealer)', 'Real', 'Animal', 'Dinosaur', 'Female', '190', '27055','0'),
('Dark Warrior', 'Real', 'Human', 'Superhero', 'Female', '60', '172','0'),
('Christiania the Mild', 'Real', 'Human', 'Knight', 'Female', '72', '208','0'),
('Calvin Sureshot Conner', 'Real', 'Human', 'Cowboy', 'Male', '60', '159','0'),
('Amethelia', 'Magical', 'Human', 'Dryad', 'Female', '61', '116','0'),
('Scarlet King', 'Real', 'Human', 'Superhero', 'Male', '81', '169','0'),
('Burford Grim Zul', 'Real', 'Human', 'Pirate', 'Male', '72', '141','2'),
('Diana Phantasm Vance', 'Real', 'Human', 'Pirate', 'Female', '66', '152','3'),
('Aunsellus the Lion', 'Real', 'Human', 'Knight', 'Male', '68', '313','2'),
('Abel the Magnificent', 'Real', 'Human', 'Knight', 'Male', '68', '240','0'),
('Thunder', 'Magical', 'Animal', 'Jackalope', 'Female', '13', '9','1'),
('Zokragrit', 'Magical', 'Animal', 'Basilisk', 'Female', '498', '398','3'),
('Georgia the Brains Wall', 'Real', 'Human', 'Cowgirl', 'Female', '66', '125','1'),
('Vesta Dishonest Norman', 'Real', 'Human', 'Pirate', 'Female', '67', '166','0'),
('Rage', 'Magical', 'Animal', 'Jackalope', 'Female', '12', '10','1'),
('Orocephalus (Mountain Head)', 'Real', 'Animal', 'Dinosaur', 'Male', '231', '24982','0'),
('Advanced Animal Handling Robot', 'Real', 'Other', 'Robot', 'Unknown', '50', '168','9'),
('Rascal', 'Magical', 'Animal', 'Wolpertinger', 'Female', '11', '6','0'),
('Professor Bloody Waspman', 'Real', 'Human', 'Supervillain', 'Male', '71', '159','0'),
('Microsuchus (Tiny Crocodile)', 'Real', 'Animal', 'Dinosaur', 'Female', '175', '27241','0'),
('Paralipus (Tidal Foot)', 'Real', 'Animal', 'Dinosaur', 'Female', '185', '18206','0'),
('Bonkers', 'Magical', 'Animal', 'Wolpertinger', 'Male', '12', '7','1'),
('Okraq', 'Magical', 'Animal', 'Basilisk', 'Male', '509', '469','10'),
('Avo Spidermint', 'Magical', 'Human', 'Fairy', 'Male', '14', '6','4'),
('Watkins Slick n Sly Cotton', 'Real', 'Human', 'Pirate', 'Male', '65', '148','0'),
('Odele Liar Driscoll', 'Real', 'Human', 'Pirate', 'Female', '68', '142','0'),
('Happy Mountainloop', 'Magical', 'Human', 'Fairy', 'Male', '13', '5','0'),
('Shuazish', 'Magical', 'Animal', 'Basilisk', 'Male', '573', '475','0'),
('Muava', 'Magical', 'Other', 'Gargoyle', 'Female', '38', '174','2'),
('The Lonely Jackal', 'Real', 'Human', 'Supervillain', 'Male', '79', '214','0'),
('Dr. Terror', 'Real', 'Human', 'Mad Scientist', 'Male', '65', '146','4'),
('Ammosaura (Sand Lizard)', 'Real', 'Animal', 'Dinosaur', 'Female', '202', '20547','2'),
('Dr. Fascination', 'Real', 'Human', 'Mad Scientist', 'Female', '66', '133','1'),
('Oscar the Snake Dale', 'Real', 'Human', 'Cowboy', 'Male', '66', '129','4'),
('Amblyantha', 'Magical', 'Human', 'Dryad', 'Female', '65', '103','0'),
('Jubal', 'Magical', 'Human', 'Merman', 'Male', '69', '196','0'),
('Balgatt', 'Magical', 'Other', 'Gargoyle', 'Male', '45', '131','0'),
('Katie the Infamous Snyder', 'Real', 'Human', 'Cowgirl', 'Female', '62', '105','7'),
('Gallop', 'Magical', 'Animal', 'Jackalope', 'Female', '14', '8','8'),
('Boaba', 'Magical', 'Human', 'Dryad', 'Female', '60', '107','0'),
('Looys the Adamant', 'Real', 'Human', 'Knight', 'Male', '67', '239','2'),
('Marisabel', 'Magical', 'Human', 'Mermaid', 'Female', '66', '136','3'),
('Datura', 'Magical', 'Human', 'Dryad', 'Female', '64', '128','9'),
('Malkyn the Honorable', 'Real', 'Human', 'Knight', 'Female', '69', '272','0'),
('Leon Noose Wright', 'Real', 'Human', 'Cowboy', 'Male', '66', '170','0'),
('Jero', 'Magical', 'Other', 'Gargoyle', 'Female', '35', '189','6'),
('Acanthocantotitan (Spiny Spined Giant)', 'Real', 'Animal', 'Dinosaur', 'Male', '171', '26659','10');




